// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ART_loadRight

#ifndef UI_CALIBRATESHOTSCREEN_H
#define UI_CALIBRATESHOTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CalibrateShotScreen
extern void ui_CalibrateShotScreen_screen_init(void);
extern void ui_CalibrateShotScreen_screen_destroy(void);
extern lv_obj_t * ui_CalibrateShotScreen;
extern void ui_event_Menu_Button1(lv_event_t * e);
extern lv_obj_t * ui_Menu_Button1;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

