// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ART_loadRight

#ifndef UI_CALIBRATEPOWDERSCREEN_H
#define UI_CALIBRATEPOWDERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CalibratePowderScreen
extern void ui_CalibratePowderScreen_screen_init(void);
extern void ui_CalibratePowderScreen_screen_destroy(void);
extern lv_obj_t * ui_CalibratePowderScreen;
extern void ui_event_Menu_Button2(lv_event_t * e);
extern lv_obj_t * ui_Menu_Button2;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

