// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ART_loadRight

#include "ui.h"

lv_obj_t * ui_CalibrateShotScreen = NULL;
lv_obj_t * ui_Menu_Button1 = NULL;
lv_obj_t * ui_Label11 = NULL;
// event funtions
void ui_event_Menu_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Menu_screen_init);
    }
}

// build funtions

void ui_CalibrateShotScreen_screen_init(void)
{
    ui_CalibrateShotScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CalibrateShotScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CalibrateShotScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalibrateShotScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu_Button1 = lv_button_create(ui_CalibrateShotScreen);
    lv_obj_set_width(ui_Menu_Button1, 65);
    lv_obj_set_height(ui_Menu_Button1, 40);
    lv_obj_set_x(ui_Menu_Button1, -79);
    lv_obj_set_y(ui_Menu_Button1, -8);
    lv_obj_set_align(ui_Menu_Button1, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Menu_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Menu_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Menu_Button1, lv_color_hex(0x585656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Menu_Button1, lv_color_hex(0x343333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Menu_Button1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Menu_Button1, &ui_img_btn_1_inact_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Menu_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Menu_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Menu_Button1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Menu_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Menu_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Menu_Button1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Menu_Button1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Menu_Button1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Menu_Button1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Menu_Button1, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Menu_Button1, &ui_img_btn_1_act_png, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label11 = lv_label_create(ui_Menu_Button1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Return");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Label11, lv_color_hex(0xF8F3F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Menu_Button1, ui_event_Menu_Button1, LV_EVENT_ALL, NULL);

}

void ui_CalibrateShotScreen_screen_destroy(void)
{
    if(ui_CalibrateShotScreen) lv_obj_del(ui_CalibrateShotScreen);

    // NULL screen variables
    ui_CalibrateShotScreen = NULL;
    ui_Menu_Button1 = NULL;
    ui_Label11 = NULL;

}
