// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ART_loadRight

#include "ui.h"

lv_obj_t * ui_CalibratePowderScreen = NULL;
lv_obj_t * ui_Menu_Button2 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Container8 = NULL;
// event funtions
void ui_event_Menu_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Menu_screen_init);
    }
}

// build funtions

void ui_CalibratePowderScreen_screen_init(void)
{
    ui_CalibratePowderScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CalibratePowderScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CalibratePowderScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalibratePowderScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Menu_Button2 = lv_button_create(ui_CalibratePowderScreen);
    lv_obj_set_width(ui_Menu_Button2, 65);
    lv_obj_set_height(ui_Menu_Button2, 40);
    lv_obj_set_x(ui_Menu_Button2, -79);
    lv_obj_set_y(ui_Menu_Button2, -8);
    lv_obj_set_align(ui_Menu_Button2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Menu_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Menu_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Menu_Button2, lv_color_hex(0x585656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Menu_Button2, lv_color_hex(0x343333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Menu_Button2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Menu_Button2, &ui_img_btn_1_inact_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Menu_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Menu_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Menu_Button2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Menu_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Menu_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Menu_Button2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Menu_Button2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Menu_Button2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Menu_Button2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Menu_Button2, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Menu_Button2, &ui_img_btn_1_act_png, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label10 = lv_label_create(ui_Menu_Button2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Return");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Label10, lv_color_hex(0xF8F3F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_CalibratePowderScreen);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 180);
    lv_obj_set_height(ui_Container8, 208);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Container8, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_Container8, LV_DIR_VER);
    lv_obj_set_scroll_snap_x(ui_Container8, LV_SCROLL_SNAP_END);

    lv_obj_add_event_cb(ui_Menu_Button2, ui_event_Menu_Button2, LV_EVENT_ALL, NULL);

}

void ui_CalibratePowderScreen_screen_destroy(void)
{
    if(ui_CalibratePowderScreen) lv_obj_del(ui_CalibratePowderScreen);

    // NULL screen variables
    ui_CalibratePowderScreen = NULL;
    ui_Menu_Button2 = NULL;
    ui_Label10 = NULL;
    ui_Container8 = NULL;

}
