// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ART_loadRight

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void update_slider_color(lv_event_t * e);
void update_shot_slider_color(lv_event_t * e);
void resetCounterCallBack(lv_event_t * e);
void alarmImageClickCallBack(lv_event_t * e);
void wifiModeSelectCallBack(lv_event_t * e);
void brightnessSliderCallBack(lv_event_t * e);
void toggleAlertCallBack(lv_event_t * e);
void toggleShowDistanceCallBack(lv_event_t * e);
void toggleShowCounterCallBack(lv_event_t * e);
void toggleShowShotCallBack(lv_event_t * e);
void ClearAllSettingsCallback(lv_event_t * e);
void measurePEmptyLevelCallBack(lv_event_t * e);
void measurePFullLevelCallBack(lv_event_t * e);
void alertPPercentCallBack(lv_event_t * e);
void measureSEmptyLevelCallBack(lv_event_t * e);
void measureSFullLevelCallBack(lv_event_t * e);
void alertSPercentCallBack(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
