// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: test

#include "ui.h"
#include <Arduino.h> // Include Arduino to use digitalWrite

void update_slider_color(lv_event_t * e)
{
	// Your code here
}

void update_shot_slider_color(lv_event_t * e)
{
	// Your code here
}

void resetCounterValue(lv_event_t * e)
{
	// Your code here
}

