// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ART_loadRight

#include "ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_BackGround = NULL;
lv_obj_t * ui_powderIndicator = NULL;
lv_obj_t * ui_powderSlider = NULL;
lv_obj_t * ui_Powder_label = NULL;
lv_obj_t * ui_powderValueLabel = NULL;
lv_obj_t * ui_powderdistValueLabel = NULL;
lv_obj_t * ui_ShotIndicator = NULL;
lv_obj_t * ui_shotSlider = NULL;
lv_obj_t * ui_Shot_Label = NULL;
lv_obj_t * ui_ShotValueLabel = NULL;
lv_obj_t * ui_shotDistValueLabel = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Menu_Button = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_CounterContainer = NULL;
lv_obj_t * ui_roundCounterLabel = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_resetCounterPanel = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_cancelRoundCntButton = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_resetCounterButton = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_alarmImage = NULL;
lv_obj_t * ui_alarmImage1 = NULL;
// event funtions
void ui_event_powderSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        update_slider_color(e);
    }
}

void ui_event_shotSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        update_shot_slider_color(e);
    }
}

void ui_event_Container2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_resetCounterPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_Menu_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Menu_screen_init);
    }
}

void ui_event_roundCounterLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_resetCounterPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_Label3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_resetCounterPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_cancelRoundCntButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_resetCounterPanel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_resetCounterButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        resetCounterCallBack(e);
    }
}

void ui_event_alarmImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        alarmImageClickCallBack(e);
    }
}

void ui_event_alarmImage1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        alarmImageClickCallBack(e);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BackGround = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_BackGround, 243);
    lv_obj_set_height(ui_BackGround, 347);
    lv_obj_set_align(ui_BackGround, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BackGround, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BackGround, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BackGround, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BackGround, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BackGround, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BackGround, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BackGround, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powderIndicator = lv_obj_create(ui_BackGround);
    lv_obj_set_width(ui_powderIndicator, lv_pct(50));
    lv_obj_set_height(ui_powderIndicator, lv_pct(100));
    lv_obj_set_y(ui_powderIndicator, 0);
    lv_obj_set_x(ui_powderIndicator, lv_pct(-30));
    lv_obj_set_align(ui_powderIndicator, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_powderIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_powderIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powderIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_powderIndicator, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_powderIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powderSlider = lv_slider_create(ui_powderIndicator);
    lv_slider_set_value(ui_powderSlider, 10, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_powderSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_powderSlider, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_powderSlider, 35);
    lv_obj_set_height(ui_powderSlider, lv_pct(72));
    lv_obj_set_x(ui_powderSlider, 5);
    lv_obj_set_y(ui_powderSlider, lv_pct(-8));
    lv_obj_set_align(ui_powderSlider, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_powderSlider, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_powderSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_powderSlider, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powderSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_powderSlider, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_powderSlider, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_powderSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_powderSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_powderSlider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_powderSlider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_powderSlider, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_powderSlider, lv_color_hex(0x11F0EA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powderSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_powderSlider, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_powderSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_powderSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_powderSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_powderSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_powderSlider,
                                                                                                   lv_obj_get_style_pad_right(ui_powderSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Powder_label = lv_label_create(ui_powderIndicator);
    lv_obj_set_width(ui_Powder_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Powder_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Powder_label, 0);
    lv_obj_set_y(ui_Powder_label, -14);
    lv_obj_set_align(ui_Powder_label, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Powder_label, "Powder");
    lv_obj_set_style_text_font(ui_Powder_label, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Powder_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Powder_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powderValueLabel = lv_label_create(ui_powderIndicator);
    lv_obj_set_width(ui_powderValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powderValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_powderValueLabel, -10);
    lv_obj_set_y(ui_powderValueLabel, lv_pct(-15));
    lv_obj_set_align(ui_powderValueLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_powderValueLabel, "100%");
    lv_obj_set_style_text_align(ui_powderValueLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_powderValueLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_powderdistValueLabel = lv_label_create(ui_powderIndicator);
    lv_obj_set_width(ui_powderdistValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_powderdistValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_powderdistValueLabel, 5);
    lv_obj_set_y(ui_powderdistValueLabel, lv_pct(34));
    lv_obj_set_align(ui_powderdistValueLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_powderdistValueLabel, "9999 mm");
    lv_obj_set_style_text_align(ui_powderdistValueLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_powderdistValueLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShotIndicator = lv_obj_create(ui_BackGround);
    lv_obj_set_width(ui_ShotIndicator, lv_pct(50));
    lv_obj_set_height(ui_ShotIndicator, lv_pct(100));
    lv_obj_set_y(ui_ShotIndicator, 0);
    lv_obj_set_x(ui_ShotIndicator, lv_pct(30));
    lv_obj_set_align(ui_ShotIndicator, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ShotIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ShotIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShotIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ShotIndicator, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ShotIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shotSlider = lv_slider_create(ui_ShotIndicator);
    lv_slider_set_value(ui_shotSlider, 10, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_shotSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_start_value(ui_shotSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_shotSlider, 35);
    lv_obj_set_height(ui_shotSlider, lv_pct(72));
    lv_obj_set_x(ui_shotSlider, -5);
    lv_obj_set_y(ui_shotSlider, lv_pct(-8));
    lv_obj_set_align(ui_shotSlider, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_shotSlider, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_shotSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_shotSlider, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shotSlider, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_shotSlider, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_shotSlider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_shotSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_shotSlider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_shotSlider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_shotSlider, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_shotSlider, lv_color_hex(0x11F0EA), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shotSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_shotSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_shotSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_shotSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_shotSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_shotSlider,
                                                                                                 lv_obj_get_style_pad_right(ui_shotSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Shot_Label = lv_label_create(ui_ShotIndicator);
    lv_obj_set_width(ui_Shot_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Shot_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Shot_Label, -5);
    lv_obj_set_y(ui_Shot_Label, -14);
    lv_label_set_text(ui_Shot_Label, "Shot");
    lv_obj_set_style_text_font(ui_Shot_Label, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Shot_Label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Shot_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShotValueLabel = lv_label_create(ui_ShotIndicator);
    lv_obj_set_width(ui_ShotValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShotValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ShotValueLabel, 10);
    lv_obj_set_y(ui_ShotValueLabel, lv_pct(-15));
    lv_obj_set_align(ui_ShotValueLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_ShotValueLabel, "100%");
    lv_obj_set_style_text_font(ui_ShotValueLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shotDistValueLabel = lv_label_create(ui_ShotIndicator);
    lv_obj_set_width(ui_shotDistValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_shotDistValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_shotDistValueLabel, -5);
    lv_obj_set_y(ui_shotDistValueLabel, lv_pct(34));
    lv_obj_set_align(ui_shotDistValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_shotDistValueLabel, "9999 mm");
    lv_obj_set_style_text_align(ui_shotDistValueLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_shotDistValueLabel, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_height(ui_Container2, 40);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 132);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_Container2, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Menu_Button = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_Menu_Button, 65);
    lv_obj_set_height(ui_Menu_Button, 40);
    lv_obj_set_x(ui_Menu_Button, -31);
    lv_obj_set_y(ui_Menu_Button, -6);
    lv_obj_set_align(ui_Menu_Button, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Menu_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Menu_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Menu_Button, lv_color_hex(0x585656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Menu_Button, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Menu_Button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Menu_Button, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Menu_Button, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Menu_Button, lv_color_hex(0x777C87), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Menu_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Menu_Button, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Menu_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Menu_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Menu_Button, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Menu_Button, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Menu_Button, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Menu_Button, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Menu_Button, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Menu_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Menu_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Menu_Button, lv_color_hex(0x585656), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Menu_Button, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_grad_color(ui_Menu_Button, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_Menu_Button, lv_color_hex(0x50FF80), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Menu_Button, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_Menu_Button, 3, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_blend_mode(ui_Menu_Button, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label5 = lv_label_create(ui_Menu_Button);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Menu");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CounterContainer = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_CounterContainer);
    lv_obj_set_width(ui_CounterContainer, 149);
    lv_obj_set_height(ui_CounterContainer, 48);
    lv_obj_set_x(ui_CounterContainer, 71);
    lv_obj_set_y(ui_CounterContainer, 132);
    lv_obj_set_align(ui_CounterContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CounterContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_CounterContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CounterContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_roundCounterLabel = lv_label_create(ui_CounterContainer);
    lv_obj_set_width(ui_roundCounterLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_roundCounterLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_roundCounterLabel, 38);
    lv_obj_set_y(ui_roundCounterLabel, 130);
    lv_obj_set_align(ui_roundCounterLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_roundCounterLabel, "10000");
    lv_obj_add_flag(ui_roundCounterLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_roundCounterLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_roundCounterLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_roundCounterLabel, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_roundCounterLabel, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label3 = lv_label_create(ui_CounterContainer);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, " Rounds");
    lv_obj_add_flag(ui_Label3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_resetCounterPanel = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_resetCounterPanel, 207);
    lv_obj_set_height(ui_resetCounterPanel, 117);
    lv_obj_set_x(ui_resetCounterPanel, 5);
    lv_obj_set_y(ui_resetCounterPanel, -22);
    lv_obj_set_align(ui_resetCounterPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_resetCounterPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_resetCounterPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_resetCounterPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_resetCounterPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_resetCounterPanel, lv_color_hex(0xFCFBFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_resetCounterPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_resetCounterPanel);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_height(ui_Container3, 44);
    lv_obj_set_width(ui_Container3, lv_pct(110));
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, 24);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cancelRoundCntButton = lv_button_create(ui_Container3);
    lv_obj_set_width(ui_cancelRoundCntButton, 65);
    lv_obj_set_height(ui_cancelRoundCntButton, 40);
    lv_obj_set_x(ui_cancelRoundCntButton, -15);
    lv_obj_set_y(ui_cancelRoundCntButton, 8);
    lv_obj_set_align(ui_cancelRoundCntButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_cancelRoundCntButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_cancelRoundCntButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_cancelRoundCntButton, lv_color_hex(0x585656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cancelRoundCntButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_cancelRoundCntButton, lv_color_hex(0x343333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_cancelRoundCntButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_cancelRoundCntButton, &ui_img_btn_1_inact_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_cancelRoundCntButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_cancelRoundCntButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cancelRoundCntButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_cancelRoundCntButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_cancelRoundCntButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_cancelRoundCntButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_cancelRoundCntButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_cancelRoundCntButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_cancelRoundCntButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_cancelRoundCntButton, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_cancelRoundCntButton, &ui_img_btn_1_act_png, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label7 = lv_label_create(ui_cancelRoundCntButton);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Cancel");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x6E0505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Label7, lv_color_hex(0xF8F3F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resetCounterButton = lv_button_create(ui_Container3);
    lv_obj_set_width(ui_resetCounterButton, 65);
    lv_obj_set_height(ui_resetCounterButton, 40);
    lv_obj_set_x(ui_resetCounterButton, -15);
    lv_obj_set_y(ui_resetCounterButton, 8);
    lv_obj_set_align(ui_resetCounterButton, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_resetCounterButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_resetCounterButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_resetCounterButton, lv_color_hex(0x585656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_resetCounterButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_resetCounterButton, lv_color_hex(0x343333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_resetCounterButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_resetCounterButton, &ui_img_btn_1_inact_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_resetCounterButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_resetCounterButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_resetCounterButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_resetCounterButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_resetCounterButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_resetCounterButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_resetCounterButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_resetCounterButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_resetCounterButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_resetCounterButton, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_resetCounterButton, &ui_img_btn_1_act_png, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label6 = lv_label_create(ui_resetCounterButton);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Reset");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Label6, lv_color_hex(0xF8F3F3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_resetCounterPanel);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label4, "Reset Round Counter");

    ui_alarmImage = lv_image_create(ui_Main);
    lv_image_set_src(ui_alarmImage, &ui_img_alarm_png);
    lv_obj_set_width(ui_alarmImage, 100);
    lv_obj_set_height(ui_alarmImage, 100);
    lv_obj_set_x(ui_alarmImage, 3);
    lv_obj_set_y(ui_alarmImage, -48);
    lv_obj_set_align(ui_alarmImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_alarmImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_alarmImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_alarmImage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_alarmImage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alarmImage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_alarmImage1 = lv_image_create(ui_Main);
    lv_image_set_src(ui_alarmImage1, &ui_img_alarm_png);
    lv_obj_set_width(ui_alarmImage1, 100);
    lv_obj_set_height(ui_alarmImage1, 100);
    lv_obj_set_x(ui_alarmImage1, 3);
    lv_obj_set_y(ui_alarmImage1, -48);
    lv_obj_set_align(ui_alarmImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_alarmImage1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_alarmImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_alarmImage1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_alarmImage1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_alarmImage1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_powderSlider, ui_event_powderSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_shotSlider, ui_event_shotSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Menu_Button, ui_event_Menu_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_roundCounterLabel, ui_event_roundCounterLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label3, ui_event_Label3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Container2, ui_event_Container2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cancelRoundCntButton, ui_event_cancelRoundCntButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_resetCounterButton, ui_event_resetCounterButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_alarmImage, ui_event_alarmImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_alarmImage1, ui_event_alarmImage1, LV_EVENT_ALL, NULL);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_BackGround = NULL;
    ui_powderIndicator = NULL;
    ui_powderSlider = NULL;
    ui_Powder_label = NULL;
    ui_powderValueLabel = NULL;
    ui_powderdistValueLabel = NULL;
    ui_ShotIndicator = NULL;
    ui_shotSlider = NULL;
    ui_Shot_Label = NULL;
    ui_ShotValueLabel = NULL;
    ui_shotDistValueLabel = NULL;
    ui_Container2 = NULL;
    ui_Menu_Button = NULL;
    ui_Label5 = NULL;
    ui_CounterContainer = NULL;
    ui_roundCounterLabel = NULL;
    ui_Label3 = NULL;
    ui_resetCounterPanel = NULL;
    ui_Container3 = NULL;
    ui_cancelRoundCntButton = NULL;
    ui_Label7 = NULL;
    ui_resetCounterButton = NULL;
    ui_Label6 = NULL;
    ui_Label4 = NULL;
    ui_alarmImage = NULL;
    ui_alarmImage1 = NULL;

}
