// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ART_loadRight

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_BackGround;
extern lv_obj_t * ui_StandardBackground;
extern lv_obj_t * ui_powderIndicator;
extern void ui_event_powderSlider(lv_event_t * e);
extern lv_obj_t * ui_powderSlider;
extern lv_obj_t * ui_Powder_label;
extern lv_obj_t * ui_powderValueLabel;
extern lv_obj_t * ui_powderdistValueLabel;
extern lv_obj_t * ui_ShotIndicator;
extern void ui_event_shotSlider(lv_event_t * e);
extern lv_obj_t * ui_shotSlider;
extern lv_obj_t * ui_Shot_Label;
extern lv_obj_t * ui_ShotValueLabel;
extern lv_obj_t * ui_shotDistValueLabel;
extern void ui_event_Container2(lv_event_t * e);
extern lv_obj_t * ui_Container2;
extern void ui_event_Menu_Button(lv_event_t * e);
extern lv_obj_t * ui_Menu_Button;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_CounterContainer;
extern void ui_event_roundCounterLabel(lv_event_t * e);
extern lv_obj_t * ui_roundCounterLabel;
extern void ui_event_Label3(lv_event_t * e);
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_resetCounterPanel;
extern lv_obj_t * ui_Container3;
extern void ui_event_cancelRoundCntButton(lv_event_t * e);
extern lv_obj_t * ui_cancelRoundCntButton;
extern lv_obj_t * ui_Label7;
extern void ui_event_resetCounterButton(lv_event_t * e);
extern lv_obj_t * ui_resetCounterButton;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label4;
extern void ui_event_alarmImage(lv_event_t * e);
extern lv_obj_t * ui_alarmImage;
extern void ui_event_alarmImage1(lv_event_t * e);
extern lv_obj_t * ui_alarmImage1;
extern lv_obj_t * ui_loadingContainer;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_primaryStartup;
extern lv_obj_t * ui_secondaryStartup;
extern lv_obj_t * ui_thirdStarup;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

