// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ART_loadRight

#ifndef UI_MENU_H
#define UI_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Menu
extern void ui_Menu_screen_init(void);
extern void ui_Menu_screen_destroy(void);
extern lv_obj_t * ui_Menu;
extern void ui_event_Return_Button(lv_event_t * e);
extern lv_obj_t * ui_Return_Button;
extern void ui_event_Label2(lv_event_t * e);
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container1;
extern void ui_event_CalibratePowderScreenButton(lv_event_t * e);
extern lv_obj_t * ui_CalibratePowderScreenButton;
extern lv_obj_t * ui_Label1;
extern void ui_event_CalibrateShotScreenButton(lv_event_t * e);
extern lv_obj_t * ui_CalibrateShotScreenButton;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label8;
extern void ui_event_EnableAlarmSwitch(lv_event_t * e);
extern lv_obj_t * ui_EnableAlarmSwitch;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label12;
extern void ui_event_showDistanceSwitch(lv_event_t * e);
extern lv_obj_t * ui_showDistanceSwitch;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label14;
extern void ui_event_showCounterSwitch(lv_event_t * e);
extern lv_obj_t * ui_showCounterSwitch;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label15;
extern void ui_event_showShotSwitch(lv_event_t * e);
extern lv_obj_t * ui_showShotSwitch;
extern lv_obj_t * ui_Label13;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

