// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: ART_loadRight

#include "ui.h"

lv_obj_t * ui_Menu = NULL;
lv_obj_t * ui_Return_Button = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_CalibratePowderScreenButton = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_CalibrateShotScreenButton = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_EnableAlarmSwitch = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_showDistanceSwitch = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_showCounterSwitch = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_showShotSwitch = NULL;
lv_obj_t * ui_Label13 = NULL;
// event funtions
void ui_event_Return_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 20, 0, &ui_Main_screen_init);
    }
}

void ui_event_Label2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Main_screen_init);
    }
}

void ui_event_CalibratePowderScreenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CalibratePowderScreen, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_CalibratePowderScreen_screen_init);
    }
}

void ui_event_CalibrateShotScreenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CalibrateShotScreen, LV_SCR_LOAD_ANIM_NONE, 10, 0, &ui_CalibrateShotScreen_screen_init);
    }
}

void ui_event_EnableAlarmSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        toggleAlertCallBack(e);
    }
}

void ui_event_showDistanceSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        toggleShowDistanceCallBack(e);
    }
}

void ui_event_showCounterSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        toggleShowCounterCallBack(e);
    }
}

void ui_event_showShotSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        toggleShowShotCallBack(e);
    }
}

// build funtions

void ui_Menu_screen_init(void)
{
    ui_Menu = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Menu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Return_Button = lv_button_create(ui_Menu);
    lv_obj_set_width(ui_Return_Button, 60);
    lv_obj_set_height(ui_Return_Button, 40);
    lv_obj_set_x(ui_Return_Button, 12);
    lv_obj_set_y(ui_Return_Button, -8);
    lv_obj_set_align(ui_Return_Button, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Return_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Return_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Return_Button, lv_color_hex(0x585656), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Return_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Return_Button, lv_color_hex(0x343333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Return_Button, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Return_Button, &ui_img_btn_1_inact_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Return_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Return_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Return_Button, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Return_Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Return_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Return_Button, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Return_Button, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Return_Button, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Return_Button, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Return_Button, LV_BLEND_MODE_ADDITIVE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Return_Button, &ui_img_btn_1_act_png, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label2 = lv_label_create(ui_Return_Button);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, lv_pct(2));
    lv_obj_set_y(ui_Label2, lv_pct(0));
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Return");

    ui_Container1 = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_height(ui_Container1, 226);
    lv_obj_set_width(ui_Container1, lv_pct(90));
    lv_obj_set_y(ui_Container1, -15);
    lv_obj_set_x(ui_Container1, lv_pct(0));
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibratePowderScreenButton = lv_button_create(ui_Container1);
    lv_obj_set_height(ui_CalibratePowderScreenButton, 30);
    lv_obj_set_width(ui_CalibratePowderScreenButton, lv_pct(100));
    lv_obj_set_align(ui_CalibratePowderScreenButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibratePowderScreenButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CalibratePowderScreenButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_CalibratePowderScreenButton, lv_color_hex(0x100E0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalibratePowderScreenButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CalibratePowderScreenButton, lv_color_hex(0x0E3556), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_CalibratePowderScreenButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(ui_CalibratePowderScreenButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_CalibratePowderScreenButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label1 = lv_label_create(ui_CalibratePowderScreenButton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Calibrate Powder Height");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrateShotScreenButton = lv_button_create(ui_Container1);
    lv_obj_set_height(ui_CalibrateShotScreenButton, 30);
    lv_obj_set_width(ui_CalibrateShotScreenButton, lv_pct(100));
    lv_obj_set_align(ui_CalibrateShotScreenButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrateShotScreenButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CalibrateShotScreenButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_CalibrateShotScreenButton, lv_color_hex(0x100E0E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CalibrateShotScreenButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CalibrateShotScreenButton, lv_color_hex(0x0E3556), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_CalibrateShotScreenButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_color(ui_CalibrateShotScreenButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_CalibrateShotScreenButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label9 = lv_label_create(ui_CalibrateShotScreenButton);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Calibrate Shot Height");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_height(ui_Container4, 20);
    lv_obj_set_width(ui_Container4, lv_pct(90));
    lv_obj_set_x(ui_Container4, 1);
    lv_obj_set_y(ui_Container4, -97);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -51);
    lv_obj_set_y(ui_Label8, 0);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Enable Alarm");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_EnableAlarmSwitch = lv_switch_create(ui_Container4);
    lv_obj_set_width(ui_EnableAlarmSwitch, 50);
    lv_obj_set_height(ui_EnableAlarmSwitch, 20);
    lv_obj_set_align(ui_EnableAlarmSwitch, LV_ALIGN_CENTER);

    ui_Container5 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_height(ui_Container5, 20);
    lv_obj_set_width(ui_Container5, lv_pct(90));
    lv_obj_set_x(ui_Container5, 1);
    lv_obj_set_y(ui_Container5, -97);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -51);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Show Distances");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_showDistanceSwitch = lv_switch_create(ui_Container5);
    lv_obj_set_width(ui_showDistanceSwitch, 50);
    lv_obj_set_height(ui_showDistanceSwitch, 20);
    lv_obj_set_align(ui_showDistanceSwitch, LV_ALIGN_CENTER);

    ui_Container6 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_height(ui_Container6, 20);
    lv_obj_set_width(ui_Container6, lv_pct(90));
    lv_obj_set_x(ui_Container6, 1);
    lv_obj_set_y(ui_Container6, -97);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -51);
    lv_obj_set_y(ui_Label14, 0);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Show Counter");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_showCounterSwitch = lv_switch_create(ui_Container6);
    lv_obj_set_width(ui_showCounterSwitch, 50);
    lv_obj_set_height(ui_showCounterSwitch, 20);
    lv_obj_set_align(ui_showCounterSwitch, LV_ALIGN_CENTER);

    ui_Container7 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_height(ui_Container7, 20);
    lv_obj_set_width(ui_Container7, lv_pct(90));
    lv_obj_set_x(ui_Container7, 1);
    lv_obj_set_y(ui_Container7, -97);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -51);
    lv_obj_set_y(ui_Label15, 0);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Show Shot");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_showShotSwitch = lv_switch_create(ui_Container7);
    lv_obj_set_width(ui_showShotSwitch, 50);
    lv_obj_set_height(ui_showShotSwitch, 20);
    lv_obj_set_align(ui_showShotSwitch, LV_ALIGN_CENTER);

    ui_Label13 = lv_label_create(ui_Menu);
    lv_obj_set_width(ui_Label13, lv_pct(100));
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_Label13, 2);
    lv_obj_set_x(ui_Label13, lv_pct(0));
    lv_obj_set_align(ui_Label13, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label13, "Main Menu");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Label2, ui_event_Label2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Return_Button, ui_event_Return_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalibratePowderScreenButton, ui_event_CalibratePowderScreenButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CalibrateShotScreenButton, ui_event_CalibrateShotScreenButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EnableAlarmSwitch, ui_event_EnableAlarmSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_showDistanceSwitch, ui_event_showDistanceSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_showCounterSwitch, ui_event_showCounterSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_showShotSwitch, ui_event_showShotSwitch, LV_EVENT_ALL, NULL);

}

void ui_Menu_screen_destroy(void)
{
    if(ui_Menu) lv_obj_del(ui_Menu);

    // NULL screen variables
    ui_Menu = NULL;
    ui_Return_Button = NULL;
    ui_Label2 = NULL;
    ui_Container1 = NULL;
    ui_CalibratePowderScreenButton = NULL;
    ui_Label1 = NULL;
    ui_CalibrateShotScreenButton = NULL;
    ui_Label9 = NULL;
    ui_Container4 = NULL;
    ui_Label8 = NULL;
    ui_EnableAlarmSwitch = NULL;
    ui_Container5 = NULL;
    ui_Label12 = NULL;
    ui_showDistanceSwitch = NULL;
    ui_Container6 = NULL;
    ui_Label14 = NULL;
    ui_showCounterSwitch = NULL;
    ui_Container7 = NULL;
    ui_Label15 = NULL;
    ui_showShotSwitch = NULL;
    ui_Label13 = NULL;

}
