// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: test

#include "ui.h"

void update_slider_color(lv_event_t * e)
{

}

void update_shot_slider_color(lv_event_t * e)
{

}
